motor:
  direction_pin: 11 # Пин направления вращения
  step_pin: 13 # Пин активации шага
  enable_pin: 15 # Пин включения питания двигателя
  direction: true # направление вращения вала
  rotation_count: 3 # Количество оборотов при вращении вала
  step_division: 0.25 # Деление шага, заданное на драйвере
  step_delay: 0.0005 # Задержка между шагами вращения (скорость вращения) в секундах